[package]
name = "rls"
version = "0.128.0"
authors = ["Nick Cameron <ncameron@mozilla.com>", "The RLS developers"]
description = "Rust Language Server - provides information about Rust programs to IDEs and other tools"
license = "Apache-2.0/MIT"
repository = "https://github.com/rust-lang-nursery/rls"
categories = ["development-tools"]

build = "build.rs"

[dependencies]
cargo = { git = "https://github.com/rust-lang/cargo", rev = "22c0f22f5621f1b68558d80a0966d073b9b68932" }
cargo_metadata = "0.5.2"
clippy_lints = { version = "0.0.205", optional = true }
env_logger = "0.5"
failure = "0.1.1"
jsonrpc-core = "8.0.1"
languageserver-types = "0.41"
lazy_static = "1"
log = "0.4"
num_cpus = "1"
racer = "2.0.14"
rayon = "1"
rls-analysis = "0.13"
rls-blacklist = "0.1.2"
rls-data = { version = "0.16", features = ["serialize-serde"] }
rls-rustc = "0.3.0"
rls-span = { version = "0.4", features = ["serialize-serde"] }
rls-vfs = { version = "0.4.5", features = ["racer-impls"] }
rustfmt-nightly = "0.8"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
url = "1.1.0"
walkdir = "2.1"

[dev-dependencies]
json = "0.11"

[features]
default = []
clippy = ["clippy_lints"]
